title: "PSRIO"
remote_theme: pmarsceill/just-the-docs
logo: https://www.psr-inc.com/wp-content/themes/psrNew/favicon.png

aux_links:
  "PSRIO Scripts on GitHub":
    - "//github.com/psrenergy/psrio-scripts"